=== amaye15/cJSON-Tools/test/benchmark_schema_small_test_4threads.json
{
	"$schema":	"http://json-schema.org/draft-07/schema#",
	"type":	"object",
	"properties":	{
		"id":	{
			"type":	"string"
		},
		"name":	{
			"type":	"string"
		},
		"email":	{
			"type":	"string"
		},
		"age":	{
			"type":	"integer"
		},
		"active":	{
			"type":	"boolean"
		},
		"address":	{
			"type":	"object",
			"properties":	{
				"street":	{
					"type":	"string"
				},
				"city":	{
					"type":	"string"
				},
				"state":	{
					"type":	"string"
				},
				"zipcode":	{
					"type":	"string"
				}
			},
			"required":	["street", "city", "state", "zipcode"]
		},
		"tags":	{
			"type":	"array",
			"items":	{
				"type":	"string"
			}
		},
		"preferences":	{
			"type":	"object",
			"properties":	{
				"notifications":	{
					"type":	"boolean"
				},
				"newsletter":	{
					"type":	"boolean"
				},
				"theme":	{
					"type":	"integer"
				},
				"display":	{
					"type":	"object",
					"properties":	{
						"fontSize":	{
							"type":	"integer"
						},
						"darkMode":	{
							"type":	"boolean"
						}
					},
					"required":	["fontSize", "darkMode"]
				}
			},
			"required":	["notifications", "newsletter", "theme", "display"]
		},
		"history":	{
			"type":	"array",
			"items":	{
				"type":	"object",
				"properties":	{
					"action":	{
						"type":	"string"
					},
					"timestamp":	{
						"type":	"integer"
					},
					"details":	{
						"type":	"object",
						"properties":	{
							"ip":	{
								"type":	"string"
							},
							"device":	{
								"type":	"string"
							}
						},
						"required":	["ip", "device"]
					}
				},
				"required":	["action", "timestamp", "details"]
			}
		}
	},
	"required":	["id", "name", "email", "age", "active", "address", "tags", "preferences", "history"]
}

=== amaye15/cJSON-Tools/test/medium_test.json
[{
		"id":	"jAf3mHVs",
		"name":	"zh5nqYoOw8",
		"email":	"ikZ0fn1R",
		"age":	50,
		"active":	true,
		"address":	{
			"street":	"WDi51nXbTIuiOnt",
			"city":	"2aFEuDNErB",
			"state":	"HE",
			"zipcode":	"qoAJa"
		},
		"tags":	["P6T1RVKn", "dS1qaSoF", "mI7XamoH"],
		"preferences":	{
			"notifications":	false,
			"newsletter":	false,
			"theme":	2,
			"display":	{
				"fontSize":	11,
				"darkMode":	false
			}
		},
		"history":	[{
				"action":	"4PQMGv",
				"timestamp":	1747909647,
				"details":	{
					"ip":	"eJwVAMVg1otx",
					"device":	"lgyxt59T"
				}
			}, {
				"action":	"RcTC6x",
				"timestamp":	1747901824,
				"details":	{
					"ip":	"G1C16bnRzYCG",
					"device":	"NQZa03yl"
				}
			}, {
				"action":	"kul49n",
				"timestamp":	1747873199,
				"details":	{
					"ip":	"zjaGO26FY7RD",
					"device":	"uD5YgJNe"
				}
			}]
	}, {
		"id":	"zFBLPTWJ",
		"name":	"S9ligjMU9I",
		"email":	"oVD5oXwj",
		"age":	54,
		"active":	false,
		"address":	{
			"street":	"TnEgQ5RwOB3vAeB",
			"city":	"FodpnJB9cw",
			"state":	"nX",
			"zipcode":	"Qvzgc"
		},
		"tags":	["LirEYLjp"],
		"preferences":	{
			"notifications":	true,
			"newsletter":	false,
			"theme":	1,
			"display":	{
				"fontSize":	12,
				"darkMode":	true
			}
		},
		"history":	[{
				"action":	"V4w7DY",
				"timestamp":	1747847184,
				"details":	{
					"ip":	"DifqZAO5AnGJ",
					"device":	"E9vegKJI"
				}
			}, {
				"action":	"ogzv0r",
				"timestamp":	1747851904,
				"details":	{
					"ip":	"VUEPlMSBBhdv",
					"device":	"HqZeTYzX"
				}
			}]
	}, {
		"id":	"48wAmAZG",
		"name":	"ogo9YSM9sv",
		"email":	"zUCAd7R2",
		"age":	94,
		"active":	false,
		"address":	{
			"street":	"PznJxH8I5Xek2sh",
			"city":	"Q8SOqbb8BB",
			"state":	"by",
			"zipcode":	"g2yEH"
		},
		"tags":	["PelmcTgY", "XqOdvubd", "6qe5oFvo", "4Beq6JeL", "LoWM72AT"],
		"preferences":	{
			"notifications":	false,
			"newsletter":	false,
			"theme":	0,
			"display":	{
				"fontSize":	14,
				"darkMode":	false
			}
		},
		"history":	[{
				"action":	"FraHmo",
				"timestamp":	1747873623,
				"details":	{
					"ip":	"HA57El3doCNC",
					"device":	"mpxeNgkR"
				}
			}, {
				"action":	"1KbLds",
				"timestamp":	1747870333,
				"details":	{
					"ip":	"KDXL8oE5QOWS",
					"device":	"2pvsBKPE"
				}
			}, {
				"action":	"nUM2Lm",
				"timestamp":	1747876001,
				"details":	{
					"ip":	"kniVYLIxJU0D",
					"device":	"BEpjuCCM"
				}
			}]
	}, {
		"id":	"2crwn98f",
		"name":	"Kj6UweDiNa",
		"email":	"ElUuOlY3",
		"age":	78,
		"active":	false,
		"address":	{
			"street":	"uUSmU7I77EaFL5o",
			"city":	"87ReLPIWA2",
			"state":	"yJ",
			"zipcode":	"Op0UJ"
		},
		"tags":	["AVtyrotU"],
		"preferences":	{
			"notifications":	true,
			"newsletter":	false,
			"theme":	2,
			"display":	{
				"fontSize":	10,
				"darkMode":	false
			}
		},
		"history":	[{
				"action":	"hQwQv2",
				"timestamp":	1747899040,
				"details":	{
					"ip":	"VTYtxcjgLRGv",
					"device":	"a2KpluC8"
				}
			}]
	}, {
		"id":	"OM85ROpw",
		"name":	"agWTZJcmLl",
		"email":	"sk3XF1Pg",
		"age":	44,
		"active":	true,
		"address":	{
			"street":	"yGXcgV6WAjiyp2h",
			"city":	"ezkpatFlks",
			"state":	"Oc",
			"zipcode":	"6SeVh"
		},
		"tags":	["IhPtdBRl", "HdAylDXt", "SWMl7VCJ", "XysZjzyP", "Ee6IDOR9"],
		"preferences":	{
			"notifications":	true,
			"newsletter":	true,
			"theme":	1,
			"display":	{
				"fontSize":	13,
				"darkMode":	false
			}
		},
		"history":	[{
				"action":	"jq4UAZ",
				"timestamp":	1747900839,
				"details":	{
					"ip":	"2zqqRfxeEcIG",
					"device":	"8e7KV6q1"
				}
			}, {
				"action":	"rezAmO",
				"timestamp":	1747864652,
				"details":	{
					"ip":	"6ekz6JPmoSHq",
					"device":	"kJYOF1Me"
				}
			}]
	}, {
		"id":	"MGsDYw1o",
		"name":	"IFGCJQ1FnE",
		"email":	"PzlmPvTE",
		"age":	64,
		"active":	false,
		"address":	{
			"street":	"tKo5gGx21oezRL0",
			"city":	"qpRTDmw2xG",
			"state":	"IQ",
			"zipcode":	"naMzt"
		},
		"tags":	["MmrgHh7T", "mvAXlOc2", "vDcRuxn0", "cA0OYhZy"],
		"preferences":	{
			"notifications":	true,
			"newsletter":	false,
			"theme":	0,
			"display":	{
				"fontSize":	14,
				"darkMode":	true
			}
		},
		"history":	[{
				"action":	"GxV5i6",
				"timestamp":	1747860079,
				"details":	{
					"ip":	"jW5MXK6kYWkm",
					"device":	"KZaPMy7Q"
				}
			}]
	}, {
		"id":	"1UZtolcj",
		"name":	"t8RCSMdFm9",
		"email":	"Q8UYlsNj",
		"age":	56,
		"active":	true,
		"address":	{
			"street":	"G33xLTOX2Q7lOOM",
			"city":	"uoN0yKEvus",
			"state":	"GL",
			"zipcode":	"4PJjj"
		},
		"tags":	["bG9SkWK0", "RTCvvXH6"],
		"preferences":	{
			"notifications":	true,
			"newsletter":	false,
			"theme":	2,
			"display":	{
				"fontSize":	13,
				"darkMode":	true
			}
		},
		"history":	[{
				"action":	"xTArw9",
				"timestamp":	1747844009,
				"details":	{
					"ip":	"GxycugnhQbYz",
					"device":	"CiTpNP0F"
				}
			}, {
				"action":	"m3UcoD",
				"timestamp":	1747877206,
				"details":	{
					"ip":	"G0A3uVrwgvHl",
					"device":	"bH7y9dfm"
				}
			}]
	}, {
		"id":	"RVam5355",
		"name":	"hywLmWEEFT",
		"email":	"1LewUd3S",
		"age":	92,
		"active":	false,
		"address":	{
			"street":	"VFcAqaNk3Gd92zI",
			"city":	"fjbHPUyoXT",
			"state":	"90",
			"zipcode":	"KPqBA"
		},
		"tags":	["B18ACir6", "mqYLZ1T0", "zyIVKtEJ", "kdmyENi3"],
		"preferences":	{
			"notifications":	false,
			"newsletter":	true,
			"theme":	0,
			"display":	{
				"fontSize":	12,
				"darkMode":	true
			}
		},
		"history":	[{
				"action":	"YxZK7M",
				"timestamp":	1747847108,
				"details":	{
					"ip":	"QA1e9MMsfkAi",
					"device":	"wXK73Bx8"
				}
			}, {
				"action":	"VpmubH",
				"timestamp":	1747845711,
				"details":	{
					"ip":	"MEUckk3mhDZy",
					"device":	"I9WOvJor"
				}
			}, {
				"action":	"BQOzz2",
				"timestamp":	1747828933,
				"details":	{
					"ip":	"R3hYDLGFUPw6",
					"device":	"WYTiuS59"
				}
			}]
	}, {
		"id":	"cClt317r",
		"name":	"oZ05R7SiHo",
		"email":	"Mr16lMU5",
		"age":	66,
		"active":	true,
		"address":	{
			"street":	"LNcLgn47d0orNfl",
			"city":	"sa3BHfbW57",
			"state":	"8H",
			"zipcode":	"Q1rVC"
		},
		"tags":	["Ve9864bU", "jrwmCOmt", "dSwcCr8y", "YOpexQ5i", "S2gMWgx5"],
		"preferences":	{
			"notifications":	true,
			"newsletter":	true,
			"theme":	2,
			"display":	{
				"fontSize":	12,
				"darkMode":	true
			}
		},
		"history":	[{
				"action":	"ev8Axy",
				"timestamp":	1747838124,
				"details":	{
					"ip":	"vXE7aGuQBCyt",
					"device":	"H9gLu96b"
				}
			}]
	}, {
		"id":	"dTutXNpn",
		"name":	"bN3uywsz0K",
		"email":	"fsbCJIBP",
		"age":	29,
		"active":	true,
		"address":	{
			"street":	"NdUQWc7HQmSPZM7",
			"city":	"o6nLWYQcXg",
			"state":	"Mv",
			"zipcode":	"FpCo2"
		},
		"tags":	["6Gp9DWNN", "EqBelPaz", "oVl4X89z", "rEPRRFkN"],
		"preferences":	{
			"notifications":	false,
			"newsletter":	true,
			"theme":	0,
			"display":	{
				"fontSize":	10,
				"darkMode":	true
			}
		},
		"history":	[{
				"action":	"fNBGSN",
				"timestamp":	1747850009,
				"details":	{
					"ip":	"QcxzlpnhmKyP",
					"device":	"ndwRn9PK"
				}
			}, {
				"action":	"KgTVju",
				"timestamp":	1747901489,
				"details":	{
					"ip":	"Na0UR0febtri",
					"device":	"F0EkdHGS"
				}
			}, {
				"action":	"UExseE",
				"timestamp":	1747846485,
				"details":	{
					"ip":	"ZLvapw07bQdf",
					"device":	"PwvXZlpa"
				}
			}]
	}, {
		"id":	"mWE5E8qW",
		"name":	"aUVYufYHBP",
		"email":	"EAtFF91Y",
		"age":	64,
		"active":	true,
		"address":	{
			"street":	"7aPkWjdpgt9gcV4",
			"city":	"w0T1pwvPP1",
			"state":	"iM",
			"zipcode":	"Q5xv2"
		},
		"tags":	["acjidwox"],
		"preferences":	{
			"notifications":	false,
			"newsletter":	false,
			"theme":	0,
			"display":	{
				"fontSize":	13,
				"darkMode":	true
			}
		},
		"history":	[{
				"action":	"54Kkq3",
				"timestamp":	1747892605,
				"details":	{
					"ip":	"3U3GzY3URqTR",
					"device":	"x1VUdiex"
				}
			}, {
				"action":	"FlImeC",
				"timestamp":	1747901242,
				"details":	{
					"ip":	"mQN7Kw0eVN7F",
					"device":	"ulo9GdUo"
				}
			}, {
				"action":	"g0sCtB",
				"timestamp":	1747829762,
				"details":	{
					"ip":	"FFBnPh1MRnBT",
					"device":	"8eQBwZOv"
				}
			}]
	}, {
		"id":	"wReKY41q",
		"name":	"msoPWP3BVS",
		"email":	"cC5Dk1H0",
		"age":	84,
		"active":	true,
		"address":	{
			"street":	"O6m8MoGAhxOtO08",
			"city":	"AEZ1pH3PAu",
			"state":	"Zr",
			"zipcode":	"1OIQs"
		},
		"tags":	["3ogfUEmi", "gFW7CkBp", "9QX3vnnj"],
		"preferences":	{
			"notifications":	true,
			"newsletter":	true,
			"theme":	2,
			"display":	{
				"fontSize":	13,
				"darkMode":	true
			}
		},
		"history":	[{
				"action":	"DKtIOb",
				"timestamp":	1747901640,
				"details":	{
					"ip":	"0hhu1cWbD9bh",
					"device":	"U2A8dJze"
				}
			}]
	}, {
		"id":	"wyYz1wQx",
		"name":	"aQyZXDjPF3",
		"email":	"Q62RbNHB",
		"age":	23,
		"active":	true,
		"address":	{
			"street":	"96PtuBTjYxHWd3J",
			"city":	"ZuSEZLkTC0",
			"state":	"Uf",
			"zipcode":	"xjM8i"
		},
		"tags":	["MC2djbZE", "GMIxlvR2", "ZED7n3X5"],
		"preferences":	{
			"notifications":	false,
			"newsletter":	true,
			"theme":	0,
			"display":	{
				"fontSize":	10,
				"darkMode":	true
			}
		},
		"history":	[{
				"action":	"gRN6VU",
				"timestamp":	1747889544,
				"details":	{
					"ip":	"KpCkV0ugHm5a",
					"device":	"N2lFOhDX"
				}
			}, {
				"action":	"ka0veI",
				"timestamp":	1747909675,
				"details":	{
					"ip":	"brR716xaRnsX",
					"device":	"TEQTfH4K"
				}
			}, {
				"action":	"l9c6ja",
				"timestamp":	1747847712,
				"details":	{
					"ip":	"FesCfJjazeyx",
					"device":	"VJPHsjl9"
				}
			}]
	}, {
		"id":	"mS2V1ZVX",
		"name":	"9VICZY23w9",
		"email":	"3VdrgX1V",
		"age":	60,
		"active":	true,
		"address":	{
			"street":	"2Dfem7XdWIZTtvj",
			"city":	"hjbaFb3ocl",
			"state":	"sZ",
			"zipcode":	"adhh5"
		},
		"tags":	["m8VhVY2s"],
		"preferences":	{
			"notifications":	true,
			"newsletter":	true,
			"theme":	2,
			"display":	{
				"fontSize":	14,
				"darkMode":	true
			}
		},
		"history":	[{
				"action":	"eUQHTK",
				"timestamp":	1747849700,
				"details":	{
