=== amaye15/cJSON-Tools/test/schema_medium_st.json
{
	"$schema":	"http://json-schema.org/draft-07/schema#",
	"type":	"object",
	"properties":	{
		"department":	{
			"type":	["object", "null"]
		},
		"tags":	{
			"type":	["array", "null"]
		},
		"active":	{
			"type":	"boolean"
		},
		"email":	{
			"type":	"string"
		},
		"name":	{
			"type":	"string"
		},
		"id":	{
			"type":	"integer"
		}
	},
	"required":	["active", "email", "name", "id"]
}

=== amaye15/cJSON-Tools/test/test_medium.json
[
  {
    "id": 1,
    "name": "John Doe",
    "email": "john@example.com",
    "active": true,
    "tags": ["admin", "user"]
  },
  {
    "id": 2,
    "name": "Jane Smith",
    "email": "jane@example.com",
    "active": false
  },
  {
    "id": 3,
    "name": "Bob Johnson",
    "email": "bob@example.com",
    "active": true,
    "department": {
      "id": 101,
      "name": "Engineering"
    }
  }
]
