=== amaye15/cJSON-Tools/test/schema_object.json
{
	"$schema":	"http://json-schema.org/draft-07/schema#",
	"type":	"object",
	"properties":	{
		"salary":	{
			"type":	"number"
		},
		"active":	{
			"type":	"boolean"
		},
		"education":	{
			"type":	"array",
			"items":	{
				"type":	"object",
				"properties":	{
					"year":	{
						"type":	"integer"
					},
					"field":	{
						"type":	"string"
					},
					"degree":	{
						"type":	"string"
					}
				},
				"required":	["year", "field", "degree"]
			}
		},
		"skills":	{
			"type":	"array",
			"items":	{
				"type":	"string"
			}
		},
		"contact":	{
			"type":	"object",
			"properties":	{
				"phone":	{
					"type":	"object",
					"properties":	{
						"mobile":	{
							"type":	"string"
						},
						"home":	{
							"type":	"string"
						}
					},
					"required":	["mobile", "home"]
				},
				"email":	{
					"type":	"string"
				}
			},
			"required":	["phone", "email"]
		},
		"address":	{
			"type":	"object",
			"properties":	{
				"zipcode":	{
					"type":	"string"
				},
				"city":	{
					"type":	"string"
				},
				"street":	{
					"type":	"string"
				}
			},
			"required":	["zipcode", "city", "street"]
		},
		"age":	{
			"type":	"integer"
		},
		"name":	{
			"type":	"string"
		}
	},
	"required":	["salary", "active", "education", "skills", "contact", "address", "age", "name"]
}

=== amaye15/cJSON-Tools/test/test_object.json
{
  "name": "John Doe",
  "age": 30,
  "address": {
    "street": "123 Main St",
    "city": "Anytown",
    "zipcode": "12345"
  },
  "contact": {
    "email": "john@example.com",
    "phone": {
      "home": "555-1234",
      "mobile": "555-5678"
    }
  },
  "skills": ["programming", "design", "communication"],
  "education": [
    {
      "degree": "Bachelor",
      "field": "Computer Science",
      "year": 2015
    },
    {
      "degree": "Master",
      "field": "Data Science",
      "year": 2018
    }
  ],
  "active": true,
  "salary": 75000.50
}
